flyway.url=jdbc:postgresql://localhost:5433/interview_manager_db
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:./migrations
flyway.baselineOnMigrate=true
flyway.cleanDisabled=true
