spring:
  application:
    name: camper-service
  web:
    resources:
      static-locations: file:/app/static/

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
